# Generated by Django 2.1.4 on 2019-09-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=16, verbose_name='用户名即真实姓名'),
        ),
    ]
